# Problem Set 2

# Question 1

## Problem 1

In [72]:
def prob1(x, y):
    '''
    This function returns some statistics of two variables x and y.
    
    Args:
        x: a scalar
        y: a scalar
        
    Returns:
        a list that contains the min, max, and mean of the items in the input list.
    '''
    summary= [min(x, y), max(x, y), (x+y)/len([x,y])]
    prob1
    return summary

prob1(1,2)

[1, 2, 1.5]

In [70]:
f= lambda x, y: [min(x, y), max(x, y), round((x+y)/len([x,y]), 2)]
f(1.05,2.796)

[1.05, 2.796, 1.92]

## Problem 2

In [75]:
num_1=2
num_1

2

In [76]:
num_2=num_1+1
num_2

3

In [80]:
num_1 == num_2

False

In [82]:
num_3=1
num_1 == num_3

False

In [78]:
# From the above, numbers are immutable

In [86]:
string_1='Yafei'
string_1

'Yafei'

In [87]:
string_2= string_1 + 'a'
string_1 == string_2

False

In [88]:
string_3 = 'a'
string_1 == string_3

False

In [89]:
# From the above, strings are immutable

In [114]:
list_1=[1, 2, 3]
list_1

[1, 2, 3]

In [115]:
list_2 = list_1

In [116]:
list_2.append(1)
list_2

[1, 2, 3, 1]

In [117]:
list_1 == list_2

True

In [118]:
# From the above, lists are mutable

In [120]:
tuple_1 = (1, 2, 3)
tuple_1

(1, 2, 3)

In [122]:
tuple_2 = tuple_1 + (1,)
tuple_2

(1, 2, 3, 1)

In [126]:
tuple_1 == tuple_2

False

In [127]:
tuple_3 = (1,)
tuple_3

(1,)

In [128]:
tuple_1 == tuple_3

False

In [129]:
# From the above, tuples are immutable

In [138]:
dict_1 = {'Country': 'U.S.', 'State': 'SC'}
dict_1

{'Country': 'U.S.', 'State': 'SC'}

In [139]:
dict_2 = dict_1

In [140]:
dict_2['Country'] = 'a'

In [141]:
dict_1 == dict_2

True

In [142]:
dict_2

{'Country': 'a', 'State': 'SC'}

In [143]:
# From the above, dictionaries are mutable

## Problem 3

In [164]:
import calculator as cal

In [ ]:
# calculator is a module that I defined in the ATOM, please see the .py file named ProblemSet2_Zhang_Calculator

In [166]:
def length(side1, side2):
    length_hypo = cal.sqr(cal.sum1(side1, side2) ** 2 - 2 * cal.prod(side1, side2))
    length
    return length_hypo

length(3,4)

5.0

# Question 2

## Problem 1

In [2]:
import numpy as np

In [7]:
np.array?

In [6]:
A = np.array([[3, -1, 4], [1, 5, -9]])
A

array([[ 3, -1,  4],
       [ 1,  5, -9]])

In [8]:
B = np.array([[2, 6, -5, 3],[5, -8, 9, 7],[9, -3, -2, -3]])
B

array([[ 2,  6, -5,  3],
       [ 5, -8,  9,  7],
       [ 9, -3, -2, -3]])

In [9]:
np.dot(A, B)

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

## Problem 2

In [10]:
A = np.array([[3, 1, 4], [1, 5, 9], [-5, 3, 1]])
A

array([[ 3,  1,  4],
       [ 1,  5,  9],
       [-5,  3,  1]])

In [11]:
np.dot(A, A, A) + np.dot(A, A) * 9 - A * 15

array([[     -27625,     -414620,  1588614795],
       [    3941035,    59672840,  -507751610],
       [-1883233064, -1191687983,  2104799283]])

In [12]:
np.arange?

In [13]:
A.dtype

dtype('int32')

In [14]:
np.zeros(4)

array([ 0.,  0.,  0.,  0.])

## Problem 5

In [33]:
A = np.arange(6).reshape((3,2)).T
AT= A.T
AT

array([[0, 1],
       [2, 3],
       [4, 5]])

In [35]:
I = np.eye(3, dtype=np.int)
B = np.tril(np.full(I.shape, 3))
B

array([[3, 0, 0],
       [3, 3, 0],
       [3, 3, 3]])

In [29]:
C = I * (-2)
C

array([[-2., -0., -0.],
       [-0., -2., -0.],
       [-0., -0., -2.]])

In [31]:
Z1 = np.zeros(9, dtype=np.int).reshape(3,3)
Z1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [37]:
Z2 = np.zeros(4, dtype=np.int).reshape(2,2)
Z2

array([[0, 0],
       [0, 0]])

In [38]:
Z3 = np.zeros(6, dtype=np.int).reshape(2,3)
Z3

array([[0, 0, 0],
       [0, 0, 0]])

In [39]:
Z4 = np.zeros(6, dtype=np.int).reshape(3,2)
Z4

array([[0, 0],
       [0, 0],
       [0, 0]])

In [45]:
np.vstack((np.hstack((Z1, AT, I)), np.hstack((A, Z2, Z3)), np.hstack((B, Z4, C))))

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2., -0., -0.],
       [ 3.,  3.,  0.,  0.,  0., -0., -2., -0.],
       [ 3.,  3.,  3.,  0.,  0., -0., -0., -2.]])

In [46]:
np.vstack((np.hstack((Z1, AT, I)), np.hstack((A, Z2, Z3)), np.hstack((B, Z4, C)))).shape

(8, 8)

# Question 3

## Problem 1

In [137]:
class backpack(object):
    def __init__(self, name, color, max_size):
        self.name = name
        self.color = color
        self.max_size = 5
        self.contents = []
        
    def put(self, item):
        if len(self.contents) < self.max_size:
            self.contents.append(item)
        else:
            print('No Room!')
            
    def dump(self, item):
        self.contents = []
        
my_backpack = backpack('Yafei', 'Blue', 5)

In [138]:
my_backpack.dump(object)
my_backpack.contents

[]

In [139]:
for item in ['Pencil', 'Pen', 'Paper', 'Computer']:
    my_backpack.put(item)
# This adds four items into the contents.

In [140]:
my_backpack.put('Note')
# This adds one more item into the contents, so now the contents includes 5 items, which is the maximun size.

In [141]:
my_backpack.contents

['Pencil', 'Pen', 'Paper', 'Computer', 'Note']

In [144]:
my_backpack.put('Pad')
# Since contents already has 5 items, there is no room for another item. This will return 'No room!' and reject the adding.

No Room!


In [145]:
my_backpack.contents

['Pencil', 'Pen', 'Paper', 'Computer', 'Note']

## Problem 2

In [261]:
class jetpack(backpack):
    def __init__(self, name = 'Yafei', color = 'Blue', max_size = 2, fuel = 10):
        self.name = name
        self.color = color
        self.max_size = max_size
        self.fuel = fuel
        self.contents = []
     
    def fly(self, burn):
        if burn < self.fuel:
            self.fuel = self.fuel - burn
        else:
            print('No enough fuel')
            self.fuel = self.fuel
    
    def dump(self, item):
        self.contents = []
        self.fuel = 0       

In [271]:
my_jetpack.dump(object)

In [272]:
my_jetpack.contents

[]

In [273]:
my_jetpack.fuel

0

In [274]:
my_jetpack = jetpack('Yafei', 'Blue', 2, 10)

In [275]:
my_jetpack.fly(5)
# The initial value of fuel is 10. If 5 are burned, then 5 will be left.

In [276]:
my_jetpack.fuel

5

In [277]:
my_jetpack.fly(2)
# Now the fuel is 5. If 2 are burned, then 3 will be left.

In [278]:
my_jetpack.fuel

3

In [279]:
my_jetpack.fly(4)
# Now the fuel is 3. 4 is beyond the remained fuel value, so it will print ' No enough fuel' and return 3.

No enough fuel


In [280]:
my_jetpack.fuel

3