# Conditional statements in python
Pretty simple

In [1]:
number = 4
if number == 4:
    print('number equals 4')

number equals 4


In [2]:
# try an else
if number > 4:
    print('number greater than 4')
else:
    print('number is not greater than 4')

number is not greater than 4


In [3]:
# try else-if
if number > 4:
    print('number greater than 4')
elif number == 4:
    print('number equals 4')
else:
    print('number is less than 4')

number equals 4


In [4]:
# test multiple conditions
if (number > 3) & (number < 10):
    print('number is in (3, 10)')

number is in (3, 10)


In [5]:
# use an OR statement
number = 11
if (number < 3) or (number > 10):
    print('number not in (3, 10)')

number not in (3, 10)


In [6]:
# with boolean
test_run = False
if test_run == True:
    print('test run')
else:
    print('not test run')

not test run


# Conditions with Numpy Arrays

In [7]:
import numpy as np

In [9]:
a = np.random.randn(5, 5)
# 5x5 matrix of numbers drawn from random normal dist
a

array([[-0.62994317,  0.16126716,  1.29289665, -0.3319534 , -0.09607577],
       [ 0.74715827, -0.57452257, -1.07387857,  0.09668097, -1.65086682],
       [ 1.45302916, -0.51558104,  0.43730397, -3.00525629,  0.96715221],
       [-2.21897776, -1.67973276,  1.32304636,  0.08240343,  2.06421689],
       [-1.75534672,  0.5491136 , -0.10012674, -0.27678677,  0.97945131]])

In [10]:
b = a > 1
b

array([[False, False,  True, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False,  True, False,  True],
       [False, False, False, False, False]], dtype=bool)

In [11]:
a * b
# True or False means 1 or zero.

array([[-0.        ,  0.        ,  1.29289665, -0.        , -0.        ],
       [ 0.        , -0.        , -0.        ,  0.        , -0.        ],
       [ 1.45302916, -0.        ,  0.        , -0.        ,  0.        ],
       [-0.        , -0.        ,  1.32304636,  0.        ,  2.06421689],
       [-0.        ,  0.        , -0.        , -0.        ,  0.        ]])

In [12]:
if a > 1:
    print('a is greater than 1')
# this is wrong because a is not a scalar but a matrix

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [13]:
if (a>1).any():
    print('some a is greater than 1')

some a is greater than 1


In [15]:
if (a>1).all():
    print('all of a is greater than 1')
else:
    print('some elements of a is not greater than 1')

some elements of a is not greater than 1


# Conditionals in Pandas

In [16]:
import pandas as pd
# data cleaning is implemented in Pandas !!!

In [19]:
data = {'school': ['Texas', 'Texas', 'Texas', 'UGA', 'UGA'], 
       'year': [2014, 2015, 2016, 2015, 2016],
       'wins':[6, 5, 5, 10 , 8]}
df = pd.DataFrame(data)
df

school  wins  year
0  Texas     6  2014
1  Texas     5  2015
2  Texas     5  2016
3    UGA    10  2015
4    UGA     8  2016

In [21]:
df['winning season'] = df['wins'] > 6
df

school  wins  year  winning season
0  Texas     6  2014           False
1  Texas     5  2015           False
2  Texas     5  2016           False
3    UGA    10  2015            True
4    UGA     8  2016            True

In [22]:
# Boolean is treated as 0, 1
this = False
number =11
this*number

0

In [23]:
# an indicator based on multiple conditions
df['winning 2016']= (df['wins'] > 6) & (df['year'] == 2016)
df

school  wins  year  winning season  winning 2016
0  Texas     6  2014           False         False
1  Texas     5  2015           False         False
2  Texas     5  2016           False         False
3    UGA    10  2015            True         False
4    UGA     8  2016            True          True

In [25]:
# conditions to slice dataframes
texas = df[df['school'] == 'Texas']
texas

school  wins  year  winning season  winning 2016
0  Texas     6  2014           False         False
1  Texas     5  2015           False         False
2  Texas     5  2016           False         False

In [26]:
# slice with multiple conditions
texas_last2 = df[(df['school'] == 'Texas') & (df['year'] > 2014)]
texas_last2

school  wins  year  winning season  winning 2016
1  Texas     5  2015           False         False
2  Texas     5  2016           False         False

# The Try Statement

In [27]:
# using the try statement
# when you created too many datasets, you may forget which one you have. Using try would avoid the error below
try:
    df = pd.read_csv('mydata.csv')
    # we don't have this dat, try to create this dataset
except:
    print('data not there')

data not there


In [28]:
df = pd.read_csv('mydata.csv')

FileNotFoundError: File b'mydata.csv' does not exist

## Is v.s. ==

In [29]:
number = 4
if number == 4:
    print('number is 4')

number is 4


In [30]:
number = 4
if number is 4:
    print('number is 4')

number is 4


In [31]:
## But is and == are not the same
# == tests equality, containing the same elements
# is tests 'identity', pointing to the exact same object
a = [1, 2, 3]
b = a
print(a)
print(b)

[1, 2, 3]
[1, 2, 3]


In [32]:
c = [1, 2, 3]

# test equality
if a == c:
    print('a equals c')

a equals c


In [33]:
# test that a and c point to the same object
if a is c:
    print('a and c are the same')
else:
    print('a and c are not the same')

a and c are not the same


In [34]:
if a is b:
    print('a and b are the same')
else:
    print('a and b are not the same')

a and b are the same


## Loops

## Types

In [36]:
# example of a for loop
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [38]:
# nesting loops
# loop in a loop
for i in range(2):
    for j in range(3):
        print(i, '+', j, '=', i+j)
    print('i =', i)

0 + 0 = 0
0 + 1 = 1
0 + 2 = 2
i = 0
1 + 0 = 1
1 + 1 = 2
1 + 2 = 3
i = 1


In [40]:
# while loop
i = 0
while i < 10:
    print(i)
    i += 1
    # add 1 to i

0
1
2
3
4
5
6
7
8
9


# Loop control statements

## Break
## continue

In [41]:
# exmaple of using break
for i in range(2):
    for j in range(3):
        print(i, '+', j, '=', i+j)
        break
        # gives you the first iteration of loop j because of the break

0 + 0 = 0
1 + 0 = 1


In [42]:
for n in range(2, 10):
    for x in range(2, n):
        if n % x == 0:
            print(n, 'equals', x, '*', n/x)
            break
    else:# goes with the for x loop
        print(n, 'is a prime number')
        

2 is a prime number
3 is a prime number
4 equals 2 * 2.0
5 is a prime number
6 equals 2 * 3.0
7 is a prime number
8 equals 2 * 4.0
9 equals 3 * 3.0


In [43]:
# example of using continue - loop to find even numbers
for num in range(2, 10):
    if num % 2 == 0:
        print('found an even number')
        continue # anything after continue is not done - go straight to the next iteration although it is within the if statement
    print('found a number')

found an even number
found a number
found an even number
found a number
found an even number
found a number
found an even number
found a number


# Nested loops with nested data

In [44]:
# make a list of lists
students = [('alex', ['compsci', 'physics']), ('justin', ['math', 'stats']), 
            ('mat', ['compsci', 'accounting', 'econ']), ('zerha', ['compsci', 'econ', 'stats'])]
students

[('alex', ['compsci', 'physics']),
 ('justin', ['math', 'stats']),
 ('mat', ['compsci', 'accounting', 'econ']),
 ('zerha', ['compsci', 'econ', 'stats'])]

In [45]:
# loop over two lists in one for loop
for (name, subjects) in students:
    print(name, 'takes', len(subjects), 'courses')

alex takes 2 courses
justin takes 2 courses
mat takes 3 courses
zerha takes 3 courses


In [46]:
for (name, subjects) in students:
    for course in subjects:
        print(name, 'takes', course)

alex takes compsci
alex takes physics
justin takes math
justin takes stats
mat takes compsci
mat takes accounting
mat takes econ
zerha takes compsci
zerha takes econ
zerha takes stats


# list comprehensions

In [48]:
all_files = ['bin', 'data', 'desktop', '.bashrc', '.ssh', '.vinrc']
all_files

['bin', 'data', 'desktop', '.bashrc', '.ssh', '.vinrc']

In [50]:
not_hidden = [name for name in all_files if name[0] != '.']
not_hidden
# a string is a sequence of characters, so name[0] refers to the first item

['bin', 'data', 'desktop']

In [51]:
numbers = [1, 2, 3, 4]
numbers ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [52]:
squares = [x ** 2 for x in numbers]
squares

[1, 4, 9, 16]

In [55]:
# list comprehensions are also fast
import time
N = 10000
start_time = time.time()
for i in range(N):
    squares = [x ** 2 for x in numbers]
end_time = time.time()
print('list comprehension time = ', end_time - start_time)

squars = []
start_time = time.time()
for i in range(N):
    for j in range(len(numbers)):
        squares.append(numbers[j] ** 2)
end_time = time.time()
print("naive loop time time =", end_time - start_time)
    

list comprehension time =  0.0190122127532959
naive loop time time = 0.0460507869720459


# looping over special data structures
## NumPy Arrays

In [57]:
import numpy as np
a = np.arange(6).reshape(2, 3) # note reshape method
a

array([[0, 1, 2],
       [3, 4, 5]])

In [58]:
for x in np.nditer(a):
    print(x)

0
1
2
3
4
5


In [60]:
for x in np.nditer(a[0, :]):
    print(x)

0
1
2
