In [1]:
print "built-in type"

three = float(3)


SyntaxError: Missing parentheses in call to 'print' (<ipython-input-1-d43c9c43a6aa>, line 1)

In [2]:
x=2
y=3
x+y

5

In [3]:
x*y

6

In [4]:
abs(2-3)

1

In [5]:
print "numeric"

SyntaxError: Missing parentheses in call to 'print' (<ipython-input-5-957b2ebd304b>, line 1)

In [6]:
print("Numeric")

Numeric


In [7]:
# calculate absolute value

# Booleans

In [8]:
drop_out= boolean

NameError: name 'boolean' is not defined

In [9]:
drop_out=False

In [10]:
type(drop_out)

bool

In [11]:
drop_out==0

True

In [12]:
x=drop_out

In [14]:
drop_out2=bool(0)
type(drop_out2)

bool

#Sequences
String

In [17]:
name=('Yafei')

In [18]:
name = 'Yafei'

In [19]:
name (-1)

TypeError: 'str' object is not callable

In [20]:
name[-1]

'i'

In [21]:
name[-]

SyntaxError: invalid syntax (<ipython-input-21-feb6d1b02a3c>, line 1)

In [22]:
name[-1]

'i'

In [23]:
name + 'Zhang'

'YafeiZhang'

In [24]:
name [3]

'e'

In [25]:
name + 2

TypeError: must be str, not int

In [26]:
name * 2

'YafeiYafei'

In [27]:
name.upper()

'YAFEI'

In [28]:
name.lower()

'yafei'

In [10]:
## Lists
lists are ordered collections of objects these objects can be different types. but usually a list contains similarly typed objects.
lists are 'mutable', which means they can change after they have been created

SyntaxError: invalid syntax (<ipython-input-10-36025b4737e9>, line 2)

In [31]:
num_list=[1,2,3]

In [32]:
num_list

[1, 2, 3]

In [33]:
num_list[1]

2

In [35]:
num_list2=[1,2,3,2]
num_list2

[1, 2, 3, 2]

In [36]:
xyz=[4,5,6]
xyz

[4, 5, 6]

In [37]:
string_list=['A','B','C',1,2,3]
string_list

['A', 'B', 'C', 1, 2, 3]

In [38]:
string_list[0]

'A'

In [39]:
string_list[-1]

3

In [40]:
xyz[:2]

[4, 5]

In [41]:
xyz[-1]=99
xyz

[4, 5, 99]

In [43]:
# you can iterate over sequences like lists
for i in xyz:
    print(i)

4
5
99


In [44]:
# strings too
for i in name:
    print(i)

Y
a
f
e
i


In [45]:
name=name.upper

In [46]:
for i in name:
    print(i)

TypeError: 'builtin_function_or_method' object is not iterable

In [47]:
name

<function str.upper>

In [48]:
name.upper

AttributeError: 'builtin_function_or_method' object has no attribute 'upper'

In [50]:
name=('Yafei')
name

'Yafei'

In [51]:
num_list+xyz

[1, 2, 3, 4, 5, 99]

In [52]:
num_list[::-1]

[3, 2, 1]

In [53]:
num_list

[1, 2, 3]

In [54]:
numlist.reverse(0)

NameError: name 'numlist' is not defined

In [55]:
numlist.reverse()

NameError: name 'numlist' is not defined

In [56]:
num_list.reverse()

In [57]:
num_list

[3, 2, 1]

In [59]:
#remove an element with a particular value
num_list.remove(3)
num_list

ValueError: list.remove(x): x not in list

In [60]:
num_list

[2, 1]

In [61]:
xyz

[4, 5, 99]

In [63]:
del(xyz[0])

In [64]:
xyz

[5, 99]

##Tuples
Tuples are ordered collections of objects. Tuples are immutable. Tuples more often contain heterogenous types of objects.

In [67]:
num_tuple=(1,2,3)
num_tuple

(1, 2, 3)

In [68]:
num_tuple[0]

1

In [69]:
for item in num_tuple:
    print(item)

1
2
3


In [70]:
num_tuple+(4,5)

(1, 2, 3, 4, 5)

In [71]:
num_tuple

(1, 2, 3)

In [72]:
num_tuple2=num_tuple+(4,5)

In [73]:
num_tuple2

(1, 2, 3, 4, 5)

In [74]:
del(num_tuple[1])

TypeError: 'tuple' object doesn't support item deletion

In [76]:
num_tuple.remove[2]

AttributeError: 'tuple' object has no attribute 'remove'

In [77]:
range(3)

range(0, 3)

In [78]:
for i in range(3):
    print(i)

0
1
2


In [79]:
for i in range(15,10,-1):
    print(i)

15
14
13
12
11


## Sets
Sets are unordered collection of unique values. They are mutable.
Useful for membership testing, uniqueness tests.

In [80]:
num_set={1,2,3}
num_set

{1, 2, 3}

In [81]:
num_set={1,2,3,4,2}

In [82]:
num_set

{1, 2, 3, 4}

In [83]:
4 in num_set

True

In [84]:
5 in num_set

False

In [85]:
num_set.remove(2)
num_set

{1, 3, 4}

In [86]:
num_set = {5,4,1,2}
num_set

{1, 2, 4, 5}

In [87]:
num_set[1]

TypeError: 'set' object does not support indexing

In [88]:
for i in num_set:
    print(i)

1
2
4
5


## Dictionaries
Dictionaries are collections of key, value pairs. Key provides pointers to associated values.
Typically, keys are strings. But they can be other types.
Dictionaries are valuable for mappings.

In [89]:
address_dict={'street': 'Greene St.', 'number': 1014, 'City': 'Columbia', 'State': 'SC'}
address_dict

{'City': 'Columbia', 'State': 'SC', 'number': 1014, 'street': 'Greene St.'}

In [90]:
address_dict['City']

'Columbia'

# Becareful with the brackets, they are important

In [91]:
for v in address_dict.values():
    print('Value = ',v)

Value =  Greene St.
Value =  1014
Value =  Columbia
Value =  SC


In [93]:
address_dict.values()

dict_values(['Greene St.', 1014, 'Columbia', 'SC'])

In [94]:
address_dict.keys()

dict_keys(['street', 'number', 'City', 'State'])

In [95]:
for k in address_dict.keys():
    print('Key = ',k)

Key =  street
Key =  number
Key =  City
Key =  State


In [96]:
for k,v in address_dict.items():
    print('Key = ',k, 'Value = ', v)

Key =  street Value =  Greene St.
Key =  number Value =  1014
Key =  City Value =  Columbia
Key =  State Value =  SC


### Numpy
Numpy is a package that is fundamental to scientific computing. It allows matrix operations and some other functionality. Like Matlab for Python

In [97]:
import numpy as np

In [98]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [99]:
A+A

array([[2, 4],
       [6, 8]])

In [100]:
A + A

array([[2, 4],
       [6, 8]])

In [101]:
A * A

array([[ 1,  4],
       [ 9, 16]])

In [102]:
np.dot(A, A)

array([[ 7, 10],
       [15, 22]])

In [103]:
np.kron(A, A)

array([[ 1,  2,  2,  4],
       [ 3,  4,  6,  8],
       [ 3,  6,  4,  8],
       [ 9, 12, 12, 16]])

In [104]:
name

'Yafei'

In [107]:
name1 = name.upper()

In [108]:
name1

'YAFEI'

In [1]:
drop_out=boolean

NameError: name 'boolean' is not defined

In [2]:
drop_out = boolean

NameError: name 'boolean' is not defined

In [3]:
drop_out=False

In [4]:
drop==0

NameError: name 'drop' is not defined

In [5]:
drop_out==0

True

In [6]:
drop_out==1

False

In [7]:
type(drop_out)

bool

In [8]:
drop_out=True

In [9]:
drop_out==1

True

In [13]:
num_list=[1,2,3]
num_list

[1, 2, 3]

In [14]:
num_list[::-2]

[3, 1]

In [15]:
num_list[::4]

[1]

In [16]:
num_list[::-4]

[3]

In [17]:
num_list[::]

[1, 2, 3]

In [18]:
num_list[::3]

[1]

In [19]:
num_list[::2]

[1, 3]

In [20]:
num_list[2]

3

In [21]:
num_list[::-3]

[3]

In [22]:
num_list[::-2]

[3, 1]

In [23]:
num_list[::2]

[1, 3]

In [24]:
num_list[1,2,3,4,5,6,7,8]

TypeError: list indices must be integers or slices, not tuple

In [25]:
num_list=[1,2,3,4,5,6,7,8]

In [26]:
num_list[::3]

[1, 4, 7]

In [27]:
num_list[::-3]

[8, 5, 2]

##the positive number after double colons gives you the numers in the positions of its multiples.
##the negative number reverses first then gives you the numbers in the positions of its multiples

In [28]:
num_list[::]

[1, 2, 3, 4, 5, 6, 7, 8]

In [29]:
num_list.remove(3)

In [30]:
num_list

[1, 2, 4, 5, 6, 7, 8]

In [31]:
range(0,3,1)

range(0, 3)

In [32]:
range

range

In [33]:
print(range)

<class 'range'>


In [34]:
for i in range(0,3,1):
    print(i)

0
1
2


In [35]:
num_set={'A',1,2,3}

In [36]:
num_set

{1, 2, 3, 'A'}

In [37]:
num_set={A,1,2,3,4,b,C,Ewad}

NameError: name 'A' is not defined

In [38]:
num_set={'A',1,2,3,4,'Ewad'}

In [39]:
num_set

{1, 2, 3, 4, 'Ewad', 'A'}

In [40]:
num_set[0]

TypeError: 'set' object does not support indexing

In [41]:
num_set{1}

SyntaxError: invalid syntax (<ipython-input-41-761450edf544>, line 1)

In [42]:
Ewad in num_set

NameError: name 'Ewad' is not defined

In [43]:
'Ewad' in num_set

True

In [44]:
np.kron[A,A,A]

NameError: name 'np' is not defined

In [45]:
import numpy as np

In [46]:
A = np.array([1,2],[3,4])

TypeError: 'builtin_function_or_method' object is not subscriptable

In [48]:
A=np.array([[1,2],[3,4]])

In [1]:
A

NameError: name 'A' is not defined

In [2]:
A

NameError: name 'A' is not defined

In [3]:
A=np.array([1,2],[3,4])

NameError: name 'np' is not defined

In [4]:
import numpy as np

In [5]:
A=np.array([1,2],[3,4])

TypeError: data type not understood

In [6]:
np.ones(2)

array([ 1.,  1.])

##Numpy and special arrays

In [7]:
np.ones((2,2))

array([[ 1.,  1.],
       [ 1.,  1.]])

In [8]:
np.zeros((2,2))

array([[ 0.,  0.],
       [ 0.,  0.]])

# Reshaping arrays

In [10]:
A.reshape((4,1))

NameError: name 'A' is not defined

In [11]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [12]:
D = np.title(A,(1,1,4))

AttributeError: module 'numpy' has no attribute 'title'

## Pandas

In [13]:
import numpy as np

In [14]:
D = np.tile(A, (1,1,4))

In [15]:
D

array([[[1, 2, 1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4, 3, 4]]])

## Pandas

In [16]:
#main object in Panda is the "dataframe" - a 2D object. Does offer advanced indexing so can represent multidimensional

In [17]:
import pandas as pd

In [19]:
# create a dictionary with some data
data = {'school': ['Texas', 'Texas', 'Texas', 'UGA', 'UGA'], 'year': [2014, 2015, 2016, 2015, 2016],
       'win': [6, 5, 5, 10, 8]}
data

{'school': ['Texas', 'Texas', 'Texas', 'UGA', 'UGA'],
 'win': [6, 5, 5, 10, 8],
 'year': [2014, 2015, 2016, 2015, 2016]}

In [20]:
frame = pd.DataFrame(data)
frame

school  win  year
0  Texas    6  2014
1  Texas    5  2015
2  Texas    5  2016
3    UGA   10  2015
4    UGA    8  2016

In [21]:
frame.columns

Index(['school', 'win', 'year'], dtype='object')

In [22]:
# to do the same thing
list(frame)

['school', 'win', 'year']

In [24]:
# to reference a paticular column
frame['win']

0     6
1     5
2     5
3    10
4     8
Name: win, dtype: int64

In [25]:
frame.wins

AttributeError: 'DataFrame' object has no attribute 'wins'

In [26]:
frame.win

0     6
1     5
2     5
3    10
4     8
Name: win, dtype: int64

In [27]:
frame.loc[0]
# loc is location

school    Texas
win           6
year       2014
Name: 0, dtype: object

In [28]:
frame.loc[1:3]

school  win  year
1  Texas    5  2015
2  Texas    5  2016
3    UGA   10  2015

In [29]:
frame.loc[0,'school']

'Texas'

In [30]:
# the first column in the above table is just the index, not considered as a column?

In [32]:
frame.groupby(['school'])['win'].sum()

school
Texas    16
UGA      18
Name: win, dtype: int64

In [33]:
frame.describe

<bound method NDFrame.describe of   school  win  year
0  Texas    6  2014
1  Texas    5  2015
2  Texas    5  2016
3    UGA   10  2015
4    UGA    8  2016>

In [34]:
frame.describe()

win        year
count   5.000000     5.00000
mean    6.800000  2015.20000
std     2.167948     0.83666
min     5.000000  2014.00000
25%     5.000000  2015.00000
50%     6.000000  2015.00000
75%     8.000000  2016.00000
max    10.000000  2016.00000

In [35]:
frame['wins sqaured']=frame['win'] ** 2

In [36]:
frame

school  win  year  wins sqaured
0  Texas    6  2014            36
1  Texas    5  2015            25
2  Texas    5  2016            25
3    UGA   10  2015           100
4    UGA    8  2016            64

In [38]:
frame.head(n=2)

school  win  year  wins sqaured
0  Texas    6  2014            36
1  Texas    5  2015            25

In [42]:
# renaming columns
frame.rename(columns={'win': 'wins', 'wins sqaured': 'win sq'}, inplace=True)
frame

school  wins  year  win sq
0  Texas     6  2014      36
1  Texas     5  2015      25
2  Texas     5  2016      25
3    UGA    10  2015     100
4    UGA     8  2016      64

In [40]:
frame

school  wins  year  wins sqaured
0  Texas     6  2014            36
1  Texas     5  2015            25
2  Texas     5  2016            25
3    UGA    10  2015           100
4    UGA     8  2016            64