In [1]:
# import packages
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# to print plots inline
%matplotlib inline

In [2]:
A = np.array([[1, 2], [3, 4]])

In [3]:
A

array([[1, 2],
       [3, 4]])

In [7]:
A.reshape(4,)

array([1, 2, 3, 4])

In [18]:
A1 = np.zeros((4,4,4))

In [19]:
A1

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [20]:
A1[:, 0] = A.reshape(4,)

In [21]:
A1

array([[[ 1.,  2.,  3.,  4.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 1.,  2.,  3.,  4.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 1.,  2.,  3.,  4.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 1.,  2.,  3.,  4.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [23]:
A = np.array([[1,2], [2,3]])

In [31]:
B = np.array([3,3])

In [26]:
A[:,1]

array([1, 2])

In [27]:
for i in range(0,2):
    C = np.multiply(A,B)

In [28]:
C

array([[2, 4],
       [4, 6]])

In [32]:
D = 1/B

In [33]:
D

array([ 0.33333333,  0.33333333])

In [38]:
E = A**2

In [39]:
E

array([[1, 4],
       [4, 9]])

In [40]:
F = np.array([1,2,3])

In [41]:
F

array([1, 2, 3])

In [49]:
G = np.transpose([F])
G

array([[1],
       [2],
       [3]])

In [45]:
A = np.array([[1,1,1], [2,2,2], [3,3,3]])

In [46]:
A

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [50]:
np.multiply(A,G)

array([[1, 1, 1],
       [4, 4, 4],
       [9, 9, 9]])

In [ ]:
C = 